# Generated by Django 4.2.6 on 2023-11-04 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('number', models.IntegerField(max_length=12)),
                ('Email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='hotel_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='guest', max_length=100)),
                ('name', models.CharField(default=None, max_length=100)),
                ('email', models.CharField(default='NA', max_length=100)),
                ('numbers_of_rooms', models.IntegerField(default=None)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
            ],
            options={
                'db_table': 'hotel_booking',
            },
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_per_room', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amenities', models.TextField()),
                ('max_persons', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='hotel_images/')),
                ('rooms', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Name', max_length=254, verbose_name='Customer Name')),
                ('amount', models.FloatField(default=0.0, verbose_name='Amount')),
                ('status', models.CharField(default='Pending', max_length=254, verbose_name='Payment Status')),
                ('provider_order_id', models.CharField(default='', max_length=40, verbose_name='Order ID')),
                ('payment_id', models.CharField(default='Default Payment ID', max_length=36, verbose_name='Payment ID')),
                ('signature_id', models.CharField(default='', max_length=128, verbose_name='Signature ID')),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('number', models.IntegerField(max_length=12)),
                ('Email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('single', 'Single Room'), ('double', 'Double Room'), ('suite', 'Suite')], max_length=100)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotels')),
            ],
        ),
    ]
